// *** AUTH TYPES
export const GET_AUTHORIZATION_TOKEN_SUCCESS = "GET_AUTHORIZATION_TOKEN_SUCCESS";
export const GET_AUTHORIZATION_TOKEN_FAILED = "GET_AUTHORIZATION_TOKEN_FAILED";

export const POST_RECEPTION_REGISTER_SUCCESS = "RECEPTION_REGISTER_SUCCESS";
export const POST_RECEPTION_REGISTER_FAILED= "RECEPTION_REGISTER_FAILED";

export const GET_RECEPTION_LOGIN_SUCCESS = "RECEPTION_LOGIN_SUCCESS";
export const GET_RECEPTION_LOGIN_FAILED= "RECEPTION_LOGIN_FAILED";

// *** VISITOR TYPES
export const GET_VISITOR_LIST_SUCCESS = "GET_VISITOR_LIST_SUCCESS";
export const GET_VISITOR_LIST_FAILED = "GET_VISITOR_LIST_FAILED";

export const GET_VISITOR_LIST_BY_ID_SUCCESS = "GET_VISITOR_LIST_BY_ID_SUCCESS";
export const GET_VISITOR_LIST_BY_ID_FAILED = "GET_VISITOR_LIST_BY_ID_FAILED";

export const POST_VISITOR_ADD_SUCCESS = "POST_VISITOR_ADD_SUCCESS";
export const POST_VISITOR_ADD_FAILED = "POST_VISITOR_ADD_FAILED";

export const PUT_VISITOR_EDIT_SUCCESS = "PUT_VISITOR_EDIT_SUCCESS";
export const PUT_VISITOR_EDIT_FAILED = "PUT_VISITOR_EDIT_FAILED";

export const VISITOR_DELETE_SUCCESS = "VISITOR_DELETE_SUCCESS";
export const VISITOR_DELETE_FAILED = "VISITOR_DELETE_FAILED";

export const ALL_VISITOR_DELETE_SUCCESS = "ALL_VISITOR_DELETE_SUCCESS";
export const ALL_VISITOR_DELETE_FAILED = "ALL_VISITOR_DELETE_FAILED";

export const GET_RECEPTIONIST_BY_ID_SUCCESS = "GET_RECEPTIONIST_BY_ID_SUCCESS";
export const GET_RECEPTIONIST_BY_ID_FAILED = "GET_RECEPTIONIST_BY_ID_FAILED";

export const PUT_RECEPTIONIST_EDIT_SUCCESS = "PUT_RECEPTIONIST_EDIT_SUCCESS";
export const PUT_RECEPTIONIST_EDIT_FAILED = "PUT_RECEPTIONIST_EDIT_FAILED";